name: Python Tests

on:
    pull_request:
        branches: [ main ]  
    workflow_dispatch:
      
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
        browser: [ "chrome", "firefox" ]
    
    services:
      selenium-hub:
        image: selenium/hub:4.34
        ports:
          - "4444:4444"
      
      chrome-node:
        image: selenium/node-chrome:112.0
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        

      firefox:
        image: selenium/node-firefox:latest
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Cache Python packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install from requirements.txt

    - name: Run tests with pytest
      run: |
        pytest --browser=${{ matrix.browser }}
    
    - name: Compress Screenshots
      uses: clydedz/compress-images@v1
      if: always()  # Ensure this step runs even if previous steps fail
      with:
        input-directory: test_reports/screenshots/
        output-directory: test_reports/screenshots/
        png-compression-quality: 0.4

    - name: Upload test report folder
      uses: actions/upload-artifact@v4
      if: always()  # Ensure this step runs even if previous steps fail
      with:
        name: test-report
        path: test_reports/
        